apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "warp10.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: "{{ template "warp10.name" . }}"
    helm.sh/chart: "{{ template "warp10.chart" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  ports:
  {{- if .Values.config.http.enabled }}
  - name: api
    port: {{ .Values.config.http.bind_address }}
    targetPort: {{ .Values.config.http.bind_address }}
  {{- end }}
  {{- if .Values.config.studio.enabled }}
  - name: studio
    port: {{ .Values.config.studio.bind_address }}
    targetPort: {{ .Values.config.studio.bind_address }}
  {{- end }}
  clusterIP: None
  selector:
    app: {{ template "warp10.name" . }}
    release: {{ .Release.Name }}
