{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "warp10.fullname" . }}"
  labels:
    app.kubernetes.io/name: "{{ template "warp10.name" . }}"
    helm.sh/chart: "{{ template "warp10.chart" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Values.ingress.secretName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "warp10.fullname" . }}
          servicePort: 8080
{{- end -}}