apiVersion: templates.sitewhere.io/v1alpha3
kind: TenantEngineConfigurationTemplate
metadata:
  name: default-schedule-management
  labels:
      sitewhere.io/functional-area: schedule-management
spec:
  configuration: 
    datastore:
      reference: default
