apiVersion: templates.sitewhere.io/v1alpha3
kind: TenantEngineConfigurationTemplate
metadata:
  name: default-device-state
  labels:
      sitewhere.io/functional-area: device-state
spec:
  configuration: 
    datastore:
      reference: default
