apiVersion: v1
appVersion: "2.0.3"
description: Helm chart for SiteWhere core Database components
name: sitewhere-infra-database
version: 0.1.7
keywords:
  - sitewhere
  - internet-of-things
  - open-source
  - iot
  - iot-framework
  - iot-platform
  - platform
  - integration
  - mongodb
home: https://sitewhere.io/
maintainers: 
  - name: Derek Adams
    email: derek.adams@sitewhere.com
  - name: Jorge Villaverde
    email: jorge.villaverde@sitewhere.com
icon: http://sitewhere.io/docs/2.0.0/images/favicon.png