dependencies:
- name: mongodb
  version: 5.2.0
  repository: https://kubernetes-charts.storage.googleapis.com
- name: cassandra
  version: 0.10.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com
  condition: sitewhere-infra-database.cassandra.enabled, cassandra.enabled
- name: influxdb
  version: 1.4.1
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: sitewhere-infra-database.influxdb.enabled, influxdb.enabled
- name: warp10
  version: 0.2.0
  repository: https://sitewhere.io/helm-charts
  condition: sitewhere-infra-database.warp10.enabled, warp10.enabled
- name: postgresql
  version: 6.5.0
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: sitewhere-infra-database.tenantsdb.enabled, tenantsdb.enabled
  alias: tenantsdb