dependencies:
- name: mongodb
  version: 5.0.1
  repository: https://kubernetes-charts.storage.googleapis.com
- name: cassandra
  version: 0.10.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com
  condition: cassandra.enabled
- name: influxdb
  version: 1.0.0
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: influxdb.enabled
