---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: tenantenginedatasets.templates.sitewhere.io
spec:
  group: templates.sitewhere.io
  names:
    categories:
    - sitewhere-io
    - core-sitewhere-io
    kind: TenantEngineDatasetTemplate
    listKind: TenantEngineDatasetTemplateList
    plural: tenantenginedatasets
    shortNames:
    - tedt
    singular: tenantenginedataset
  scope: Cluster
  versions:
  - name: v1alpha4
    schema:
      openAPIV3Schema:
        description: TenantEngineDatasetTemplate is the Schema for the tenantenginedatasets API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TenantEngineDatasetTemplateSpec defines the desired state of TenantEngineDatasetTemplate
            properties:
              configuration:
                description: Configuration is the configuration for the tenant
                nullable: true
                type: string
            type: object
          status:
            description: TenantEngineDatasetTemplateStatus defines the observed state of TenantEngineDatasetTemplate
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
