apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitewhere-operator
  namespace: sitewhere-system
  labels:
    app: sitewhere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitewhere-operator
  template:
    metadata:
      labels:
        app: sitewhere-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: sitewhere-operator-service-account
      containers:
      - name: operator
        image: sitewhere/sitewhere-k8s-operator:3.0.0.alpha6
