apiVersion: v1
appVersion: "2.1"
description: SiteWhere 2.1 Helm chart for Kubernetes using Default configuration
name: sitewhere
version: 0.2.1
description: SiteWhere is an industrial strength open-source application enablement platform for the Internet of Things (IoT). It provides a multi-tenant microservice-based infrastructure that includes device/asset management, data ingestion, big-data storage, and integration through a modern, scalable architecture.
keywords:
  - sitewhere
  - internet-of-things
  - integration
  - device-management
  - iot
  - iot-platform
  - platform
  - mqtt
  - iot-framework
  - java
  - arduino
  - raspberry-pi
  - android
  - m2x
  - hbase
  - open-source
  - aws
  - kafka
  - zookeeper
  - microservices
home: http://www.sitewhere.org/
maintainers: 
  - name: Derek Adams
    email: derek.adams@sitewhere.com
  - name: Jorge Villaverde
    email: jorge.villaverde@sitewhere.com
icon: http://sitewhere.io/docs/2.0.0/images/favicon.png


