dependencies:
- name: sitewhere-infra-core
  version: 0.1.3
  repository: https://sitewhere.io/helm-charts
- name: sitewhere-infra-database
  version: 0.1.4
  repository: https://sitewhere.io/helm-charts
