apiVersion: templates.sitewhere.io/v1alpha4
kind: TenantEngineConfigurationTemplate
metadata:
  name: default-batch-operations
  labels:
      sitewhere.io/functional-area: batch-operations
spec:
  configuration:
    datastore:
      reference: postgres
    batchOperationManager:
      throttleDelayMs: 100
