apiVersion: scripting.sitewhere.io/v1alpha3
kind: SiteWhereScriptTemplate
metadata:
  name: outbound-connectors-payload-builder
  labels:
    sitewhere.io/functional-area: outbound-connectors
    scripting.sitewhere.io/category: outbound-connectors-payload-builder-category
spec:
  name: Payload Builder
  description: Implements a payload builder.
  interpreterType: js
  script: |
    // Available variable bindings:
    // ----------------------------
    // context: (IDeviceEventContext) Context information associated with device event.
    // event: (IDeviceEvent) Current device event being processed by connector.
    // assignment: (IDeviceAssignment) Assignment associated with invocation event.
    // device: (IDevice) Information about device related to event.
    // logger: (Logger) Supports output to system logs.
    // ----------------------------
    // return value (byte[]): Binary array containing payload content.
    // ----------------------------
    
    String payload = String.format("{ 'deviceToken': '%s' }", device.getToken())
    logger.info String.format("HTTP connector using payload:: %s", payload)
    return payload.getBytes("UTF-8")
