---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: tenants.sitewhere.io
spec:
  group: sitewhere.io
  names:
    categories:
    - sitewhere-io
    - core-sitewhere-io
    kind: SiteWhereTenant
    listKind: SiteWhereTenantList
    plural: tenants
    shortNames:
    - swt
    singular: tenant
  scope: Namespaced
  versions:
  - name: v1alpha4
    schema:
      openAPIV3Schema:
        description: SiteWhereTenant is the Schema for the tenants API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SiteWhereTenantSpec defines the desired state of SiteWhereTenant
            properties:
              authenticationToken:
                description: AuthenticationToken is the token used for authenticating the tenant
                type: string
              authorizedUserIds:
                description: Authorized are the IDs of the users that are authorized to use the tenant
                items:
                  type: string
                type: array
              branding:
                description: Branding is the branding information for the tenant
                properties:
                  backgroundColor:
                    description: BackgroundColor is the background color of the branding
                    type: string
                  borderColor:
                    description: BorderColor is the border color of the branding
                    type: string
                  foregroundColor:
                    description: ForegroundColor is the foreground color of the branding
                    type: string
                  icon:
                    description: Icon is the icon of the branding
                    type: string
                  imageUrl:
                    description: ImageURL is the image URL of the branding
                    type: string
                type: object
              configurationTemplate:
                description: ConfigurationTemplate is the configuration template used for the tenant
                type: string
              datasetTemplate:
                description: DatasetTemplate is the dataset template used for the tenant
                type: string
              metadata:
                additionalProperties:
                  type: string
                description: Metadata is the metadata of the tenant
                type: object
              name:
                description: Name is the name of the tenant (ObjectMeta.name)
                type: string
            type: object
          status:
            description: SiteWhereTenantStatus defines the observed state of SiteWhereTenant
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
