{{- if include "microservices.asset_management.enabled" . }}
{{$data := dict "Values" .Values.services.asset_management "Defaults" .Values.services }}
apiVersion: sitewhere.io/v1alpha3
kind: SiteWhereMicroservice
metadata:
  name: asset-management-microservice
spec:
  replicas: {{ .Values.services.asset_management.replicaCount }}
  instanceName: {{ include "sitewhere.name" . }}
  functionalArea: asset-management
  helm:
    chartName: {{ include "sitewhere.chart" . }}
    releaseName: {{ include "sitewhere.name" . }}
    releaseService: Tiller
  podSpec:
    imageRegistry: {{ .Values.services.image.registry }}
    imageRepository: {{ .Values.services.image.repository }}
    imageTag: {{ .Values.services.image.tag }}
    imagePullPolicy: {{ .Values.services.image.pullPolicy }}
    ports:
      - containerPort: 9000
      - containerPort: 9001
      - containerPort: {{ .Values.services.metrics.port }}
{{include "sitewhere.microservice.envValues" . | indent 4 }}
{{include "sitewhere.microservice.resources" $data | indent 4 }}
{{include "sitewhere.microservice.probes" . | indent 4 }}
{{include "sitewhere.microservice.imagePullSecrets" . | indent 4 }}
  serviceSpec:
    type: LoadBalancer
    ports:
      - port: 9000
        targetPort: {{ .Values.services.asset_management.service.grpc.api.port }}
        protocol: TCP
        name: grpc-api
      - port: 9001
        targetPort: {{ .Values.services.asset_management.service.grpc.management.port }}
        protocol: TCP
        name: grpc-management
      - port: {{ .Values.services.metrics.port }}
        targetPort: {{ .Values.services.metrics.port }}
        protocol: TCP
        name: http-metrics
  debug:
    enabled: false
    jdwpPort: 8006
    jmxPort: 1106
{{- end }}
