{{- if include "microservices.event_sources.enabled" . }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sitewhere.fullname" . }}-event-sources
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    sitewhere.io/role: "microservice"
    sitewhere.io/name: "event-sources"
spec:
  replicas: {{ .Values.services.event_sources.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere.name" . }}-event-sources
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere.name" . }}-event-sources
        app.kubernetes.io/instance: {{ .Release.Name }}
        sitewhere.io/role: "microservice"
        sitewhere.io/name: "event-sources"
    spec:
      containers:
        - name: {{ .Chart.Name }}-event-sources
{{- if .Values.services.debug }}
          image: "{{ .Values.services.image.registry }}/{{ .Values.services.image.repository }}/{{ .Values.services.event_sources.image }}:debug-{{ .Values.services.image.tag }}"
{{- else }}
          image: "{{ .Values.services.image.registry }}/{{ .Values.services.image.repository }}/{{ .Values.services.event_sources.image }}:{{ .Values.services.image.tag }}"
{{- end }}
          imagePullPolicy: {{ .Values.services.image.pullPolicy }}
          ports:
            - containerPort: 9001
{{- if .Values.services.debug }}
            - containerPort: 8001
            - containerPort: 1107
{{- end }}
          env:
{{ include "sitewhere.microserviceEnvValues" . | indent 12 }}
{{- include "sitewhere.services.imagePullSecrets" . | indent 6 }}
          resources:
            limits:
              memory: {{ .Values.services.event_sources.resources.limits.memory | default .Values.services.resources.limits.memory | quote }}
              cpu: {{ .Values.services.event_sources.resources.limits.cpu | default .Values.services.resources.limits.cpu | quote }}
            requests:
              memory: {{ .Values.services.event_sources.resources.requests.memory | default .Values.services.resources.requests.memory | quote }}
              cpu: {{ .Values.services.event_sources.resources.requests.cpu | default .Values.services.resources.requests.cpu | quote }}
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.services.health.port }}"]
            initialDelaySeconds: {{ .Values.services.health.readinessProbe.initialDelay }}
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.services.health.port }}"]
            initialDelaySeconds: {{ .Values.services.health.livenessProbe.initialDelay }}
            periodSeconds: {{ .Values.services.health.livenessProbe.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-event-sources-svc
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.services.event_sources.service.type }}
  ports:
    - port: 9001
      targetPort: {{ .Values.services.event_sources.service.grpc.management.port }}
      protocol: TCP
      name: grpc-management
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-event-sources
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.services.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-event-sources-debug
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8007
      protocol: TCP
      name: jdwp
    - port: 1107
      targetPort: 1107
      protocol: TCP
      name: jmx
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-event-sources
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
