{{- if include "microservices.inbound_processing.enabled" . }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sitewhere.fullname" . }}-inbound-processing
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.services.inbound_processing.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere.name" . }}-inbound-processing
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere.name" . }}-inbound-processing
        app.kubernetes.io/instance: {{ .Release.Name }}
        sitewhere.io/role: "microservice"
        sitewhere.io/name: "inbound-processing"
    spec:
      containers:
        - name: {{ .Chart.Name }}-inbound-processing
{{ if .Values.services.debug }}
          image: "{{ .Values.services.image.registry }}/{{ .Values.services.image.repository }}/{{ .Values.services.inbound_processing.image }}:debug-{{ .Values.services.image.tag }}"
{{ else }}
          image: "{{ .Values.services.image.registry }}/{{ .Values.services.image.repository }}/{{ .Values.services.inbound_processing.image }}:{{ .Values.services.image.tag }}"
{{ end }}
          imagePullPolicy: {{ .Values.services.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.inbound_processing.service.grpc.api.port }}
            - containerPort: {{ .Values.services.inbound_processing.service.grpc.management.port }}
{{- if .Values.services.debug }}
            - containerPort: 8001
            - containerPort: 1108
{{- end }}
          env:
{{ include "sitewhere.microserviceEnvValues" . | indent 12 }}
{{ include "sitewhere.initContainers" . | indent 6 }}
{{ include "sitewhere.services.imagePullSecrets" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-inbound-processing-svc
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.services.inbound_processing.service.type }}
  ports:
    - port: {{ .Values.services.inbound_processing.service.grpc.api.port }}
      targetPort: {{ .Values.services.inbound_processing.service.grpc.api.port }}
      protocol: TCP
      name: grcp-api
    - port: {{ .Values.services.inbound_processing.service.grpc.management.port }}
      targetPort: {{ .Values.services.inbound_processing.service.grpc.management.port }}
      protocol: TCP
      name: grcp-mgn
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-inbound-processing
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.services.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-inbound-processing-debug
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8008
      protocol: TCP
      name: jdwp
    - port: 1108
      targetPort: 1108
      protocol: TCP
      name: jmx
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-inbound-processing
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
