apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sitewhere.fullname" . }}-mosquitto
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.infra.mosquitto.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere.name" . }}-mosquitto
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere.name" . }}-mosquitto
        app.kubernetes.io/instance: {{ .Release.Name }}
        sitewhere.io/role: "infraestructure"
        sitewhere.io/name: "mosquitto"
    spec:
      containers:
        - name: {{ .Chart.Name }}-mosquitto
          image: "{{ .Values.infra.image.registry }}/{{ .Values.infra.mosquitto.image }}"
          imagePullPolicy: {{ .Values.infra.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.infra.mosquitto.service.port }}
              name: mosquitto-port
              protocol: TCP
{{ include "sitewhere.infra.imagePullSecrets" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-mosquitto-svc
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.infra.mosquitto.service.type }}
  ports:
    - port: {{ .Values.infra.mosquitto.service.port }}
      targetPort: {{ .Values.infra.mosquitto.service.port }}
      protocol: TCP
      name: mosquitto-port
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}

