{{- if include "microservices.outbound_connectors.enabled" . }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sitewhere.fullname" . }}-outbound-connectors
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    sitewhere.io/role: "microservice"
    sitewhere.io/name: "outbound-connectors"
spec:
  replicas: {{ .Values.services.outbound_connectors.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere.name" . }}-outbound-connectors
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere.name" . }}-outbound-connectors
        app.kubernetes.io/instance: {{ .Release.Name }}
        sitewhere.io/role: "microservice"
        sitewhere.io/name: "outbound-connectors"
    spec:
      containers:
        - name: {{ .Chart.Name }}-outbound-connectors
{{- if .Values.services.debug }}
          image: "{{ .Values.services.image.registry }}/{{ .Values.services.image.repository }}/{{ .Values.services.outbound_connectors.image }}:debug-{{ .Values.services.image.tag }}"
{{- else }}
          image: "{{ .Values.services.image.registry }}/{{ .Values.services.image.repository }}/{{ .Values.services.outbound_connectors.image }}:{{ .Values.services.image.tag }}"
{{- end }}
          imagePullPolicy: {{ .Values.services.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.outbound_connectors.service.grpc.api.port }}
            - containerPort: {{ .Values.services.outbound_connectors.service.grpc.management.port }}
{{- if .Values.services.debug }}
            - containerPort: 8001
            - containerPort: 1116
{{- end }}
          env:
{{ include "sitewhere.microserviceEnvValues" . | indent 12 }}
{{- include "sitewhere.services.imagePullSecrets" . | indent 6 }}
          resources:
            limits:
              memory: {{ .Values.services.outbound_connectors.resources.limits.memory | default .Values.services.resources.limits.memory | quote }}
              cpu: {{ .Values.services.outbound_connectors.resources.limits.cpu | default .Values.services.resources.limits.cpu | quote }}
            requests:
              memory: {{ .Values.services.outbound_connectors.resources.requests.memory | default .Values.services.resources.requests.memory | quote }}
              cpu: {{ .Values.services.outbound_connectors.resources.requests.cpu | default .Values.services.resources.requests.cpu | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-outbound-connectors-svc
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.services.outbound_connectors.service.type }}
  ports:
    - port: {{ .Values.services.outbound_connectors.service.grpc.api.port }}
      targetPort: {{ .Values.services.outbound_connectors.service.grpc.api.port }}
      protocol: TCP
      name: grcp-api
    - port: {{ .Values.services.outbound_connectors.service.grpc.management.port }}
      targetPort: {{ .Values.services.outbound_connectors.service.grpc.management.port }}
      protocol: TCP
      name: grcp-mgn
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-outbound-connectors
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.services.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-outbound-connectors-debug
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8016
      protocol: TCP
      name: jdwp
    - port: 1116
      targetPort: 1116
      protocol: TCP
      name: jmx
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-outbound-connectors
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
